model_list:
  - model_name: "*"
    litellm_params:
      model: os.environ/LITELLM_MODEL
      api_base: os.environ/OLLAMA_BASE_URL

litellm_settings:
  drop_params: true
  set_verbose: false

general_settings:
  master_key: sk-local-anything
